export const getAuthUserId = (state) => state.auth.authId
export const getAuthUserName = (state) => state.auth.userName
export const getUserImages = state => state.auth.userImages
export const getAuth = (state) => state.auth.isAuth
export const getRegMessage = (state) => state.auth.regMessage
export const getAuthAbout = state => state.auth.about
export const getAuthPhone = state => state.auth.phone
export const getAuthAddress = state => state.auth.address
export const getAuthEmail = state => state.auth.email