export const SET_USER_DATA = 'AUTH/SET_AUTH';
export const REGISTRATION_MESSAGE = "AUTH/REGISTRATION_MESSAGE";
export const UPDATE_USER_DATA = 'AUTH/UPDATE_USER_DATA'
export const UPDATE_AUTH_IMAGES = 'AUTH/UPDATE_AUTH_IMAGES'