export const SUBSCRIBE = "USERS-PAGE/SUBSCRIBE";
export const UNSUBSCRIBE = "USERS-PAGE/UNSUBSCRIBE";
export const SET_USERS = "USERS-PAGE/SET_USERS";
export const SET_PAGE = "USERS-PAGE/SET_PAGE";
export const TOGGLE_LOADING_USERS = "USERS-PAGE/TOGGLE_LOADING_USERS";
export const TOGGLE_FOLLOWING_ON_USER = "USERS-PAGE/TOGGLE_FOLLOWING_ON_USER";
export const SET_HAVE_USERS = "USERS-PAGE/SET_HAVE_USERS";
export const SET_SUBSCRIBERS = "USERS-PAGE/SET_SUBSCRIBERS";