export const ADD_POST = 'PROFILE-PAGE/ADD-POST';
export const SET_PROFILE_DATA = 'PROFILE-PAGE/SET_PROFILE_DATA';
export const TOGGLE_LOADING_USER = 'PROFILE-PAGE/TOGGLE_LOADING_USER';
export const DELETE_POST = 'PROFILE-PAGE/DELETE_POST';