export const ADD_NEW_MESSAGE = 'DIALOGS-PAGE/ADD_NEW_MESSAGE'
export const SET_DIALOGS = 'DIALOGS-PAGE/SET_DIALOGS'
export const SET_ACTIVE_DIALOG = 'DIALOGS-PAGE/SET_ACTIVE_DIALOG'
export const TOGGLE_LOADING = 'DIALOGS-PAGE/TOGGLE_LOADING'